/**
 * Historic team collection challenges — the generator.
 *
 * One iconic season from every active franchise, pre-built: the starting
 * lineup (plus a DH where the era had one) and the pitching staff, read
 * straight out of the cached Lahman CSVs. The output is committed at
 * `packages/shared/src/historicTeams.ts`, so the app itself never needs the
 * CSVs at runtime and the catalog is reviewable in code review.
 *
 *   pnpm --filter @cardball/import-stats challenges [-- --check]
 *
 * `--check` re-runs the generator and fails if the committed file drifted,
 * so CI keeps the catalog honest against the current data.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadCsvFiles } from './download.js';
import { PICKS } from './picks.js';
import type { Pick } from './picks.js';
import { buildTeam, loadPeople } from './rosterBuilder.js';
import type { PlayerRow } from './rosterBuilder.js';

function renderFile(teams: { pick: Pick; players: PlayerRow[] }[]): string {
  const lines: string[] = [
    '/**',
    ' * Historic team collection challenges.',
    ' *',
    ' * One iconic season from every active franchise, with its lineup pre-built',
    ' * from the record books: collect a card covering the season for every player',
    ' * listed and the collection is complete.',
    ' *',
    ' * GENERATED by `pnpm --filter @cardball/import-stats challenges` from the',
    ' * cached Lahman CSVs — edit the picks in tools/import-stats/src/challenges.ts',
    ' * and re-run; do not hand-edit the players.',
    ' */',
    '',
    "export interface HistoricPlayer {",
    "  /** Baseball-Reference id, matching `people.bbref_id` in the database */",
    '  bbrefId: string;',
    '  name: string;',
    '  /** lineup slot: C, 1B, 2B, 3B, SS, LF, CF, RF, DH, SP, RP */',
    '  position: string;',
    '}',
    '',
    'export interface HistoricTeam {',
    "  /** stable slug, e.g. 'sea-1995' */",
    '  id: string;',
    '  year: number;',
    '  /** what the team was called that season, e.g. “1955 Brooklyn Dodgers” */',
    '  name: string;',
    '  /** the franchise today, e.g. “Los Angeles Dodgers” */',
    '  franchise: string;',
    '  tagline: string;',
    '  players: HistoricPlayer[];',
    '}',
    '',
    'export const HISTORIC_TEAMS: readonly HistoricTeam[] = [',
  ];
  for (const { pick, players } of teams) {
    lines.push('  {');
    lines.push(`    id: '${pick.teamId.toLowerCase()}-${pick.year}',`);
    lines.push(`    year: ${pick.year},`);
    lines.push(`    name: ${JSON.stringify(pick.name)},`);
    lines.push(`    franchise: ${JSON.stringify(pick.franchise)},`);
    lines.push(`    tagline: ${JSON.stringify(pick.tagline)},`);
    lines.push('    players: [');
    for (const player of players) {
      lines.push(`      { bbrefId: ${JSON.stringify(player.bbrefId)}, name: ${JSON.stringify(player.name)}, position: ${JSON.stringify(player.position)} },`);
    }
    lines.push('    ],');
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  lines.push('export function historicTeamById(id: string): HistoricTeam | undefined {');
  lines.push('  return HISTORIC_TEAMS.find((team) => team.id === id);');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const OUTPUT_PATH = fileURLToPath(new URL('../../../packages/shared/src/historicTeams.ts', import.meta.url));

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const files = await loadCsvFiles({ log: () => undefined });
  const people = loadPeople(files['People.csv'] ?? '');
  const teams: { pick: Pick; players: PlayerRow[] }[] = [];
  const warnings: string[] = [];
  const ids = new Set<string>();
  for (const pick of PICKS) {
    const id = `${pick.teamId.toLowerCase()}-${pick.year}`;
    if (ids.has(id)) throw new Error(`Duplicate challenge id ${id}`);
    ids.add(id);
    const built = buildTeam(files, people, pick);
    warnings.push(...built.warnings);
    if (built.players.length === 0) throw new Error(`${pick.name}: no players found — wrong teamID or year?`);
    teams.push({ pick, players: built.players });
  }

  const text = renderFile(teams);
  if (check) {
    const committed = await readFile(OUTPUT_PATH, 'utf8');
    if (committed !== text) {
      console.error('The committed historicTeams.ts is out of date — re-run the generator.');
      process.exitCode = 1;
    } else {
      console.log(`${PICKS.length} challenges, up to date.`);
    }
    return;
  }

  await writeFile(OUTPUT_PATH, text, 'utf8');
  console.log(`Wrote ${teams.length} challenges to ${OUTPUT_PATH}`);
  for (const warning of warnings) console.warn(`  warning: ${warning}`);
}

try {
  await main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
