/**
 * Stock bot teams — the generator.
 *
 * The Vs. Bot opponent picker used to offer only a manager's own teams, so a
 * manager with a single team had nobody to play. These are ready-made
 * opponents: the same iconic team-seasons as the collection challenges, but
 * built as full, game-ready rosters — the eight fielders and the designated
 * hitter the engine requires, a real starting pitcher, a bullpen, and a bench.
 *
 * The output is committed at `packages/shared/src/stockTeams.ts`. Each roster
 * is checked against the live database by the server test suite, which builds
 * every team's cards and asserts a legal lineup, so the catalog cannot drift
 * out of the engine's rules unnoticed.
 *
 *   pnpm --filter @cardball/import-stats stock-teams [-- --check]
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadCsvFiles } from './download.js';
import { PICKS } from './picks.js';
import type { Pick } from './picks.js';
import { buildStockRoster, loadPeople } from './rosterBuilder.js';
import type { PlayerRow } from './rosterBuilder.js';

/** How many teams to ship; enough spread across eras to be a real choice. */
const STOCK_PICKS: readonly Pick[] = PICKS;

function renderFile(teams: { pick: Pick; players: PlayerRow[] }[]): string {
  const lines: string[] = [
    '/**',
    ' * Stock bot teams: ready-made opponents for a game against the bot.',
    ' *',
    ' * Each is an iconic team-season with a full, game-ready roster — the eight',
    ' * fielders and the designated hitter the engine requires, a starting',
    ' * pitcher, a bullpen, and a bench. The `position` on each player records the',
    ' * slot the record books put him in; the server derives the actual preset',
    ' * lineup from the roster with the same auto-lineup the manager uses, so a',
    ' * stock team is always legal under the current house rules.',
    ' *',
    ' * GENERATED by `pnpm --filter @cardball/import-stats stock-teams` from the',
    ' * cached Lahman CSVs — edit the picks in tools/import-stats/src/picks.ts and',
    ' * re-run; do not hand-edit the players.',
    ' */',
    '',
    'export interface StockPlayer {',
    "  /** Baseball-Reference id, matching `people.bbref_id` in the database */",
    '  bbrefId: string;',
    '  name: string;',
    '  /** intended slot: C, 1B, 2B, 3B, SS, LF, CF, RF, DH, SP, or RP */',
    '  position: string;',
    '}',
    '',
    'export interface StockTeam {',
    "  /** stable slug, e.g. 'nya-1961' */",
    '  id: string;',
    '  year: number;',
    '  name: string;',
    '  tagline: string;',
    '  players: StockPlayer[];',
    '}',
    '',
    'export const STOCK_TEAMS: readonly StockTeam[] = [',
  ];
  for (const { pick, players } of teams) {
    lines.push('  {');
    lines.push(`    id: '${pick.teamId.toLowerCase()}-${pick.year}',`);
    lines.push(`    year: ${pick.year},`);
    lines.push(`    name: ${JSON.stringify(pick.name)},`);
    lines.push(`    tagline: ${JSON.stringify(pick.tagline)},`);
    lines.push('    players: [');
    for (const player of players) {
      lines.push(`      { bbrefId: ${JSON.stringify(player.bbrefId)}, name: ${JSON.stringify(player.name)}, position: ${JSON.stringify(player.position)} },`);
    }
    lines.push('    ],');
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  lines.push('export function stockTeamById(id: string): StockTeam | undefined {');
  lines.push('  return STOCK_TEAMS.find((team) => team.id === id);');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const OUTPUT_PATH = fileURLToPath(new URL('../../../packages/shared/src/stockTeams.ts', import.meta.url));

/** The structural shape a stock roster must have before the server can field it. */
function checkShape(name: string, players: PlayerRow[]): void {
  const positions = players.map((p) => p.position);
  for (const pos of ['C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 'DH']) {
    if (!positions.includes(pos)) throw new Error(`${name}: no ${pos} in the roster`);
  }
  if (!positions.includes('SP')) throw new Error(`${name}: no starting pitcher in the roster`);
  if (positions.filter((p) => p === 'RP').length < 2) throw new Error(`${name}: fewer than two relievers in the roster`);
  if (new Set(players.map((p) => p.bbrefId)).size !== players.length) throw new Error(`${name}: duplicate player in the roster`);
  if (players.length > 26) throw new Error(`${name}: roster of ${players.length} is over the 26-card limit`);
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const files = await loadCsvFiles({ log: () => undefined });
  const people = loadPeople(files['People.csv'] ?? '');
  const teams: { pick: Pick; players: PlayerRow[] }[] = [];
  const warnings: string[] = [];
  const ids = new Set<string>();
  for (const pick of STOCK_PICKS) {
    const id = `${pick.teamId.toLowerCase()}-${pick.year}`;
    if (ids.has(id)) throw new Error(`Duplicate stock team id ${id}`);
    ids.add(id);
    const built = buildStockRoster(files, people, pick);
    warnings.push(...built.warnings);
    checkShape(pick.name, built.players);
    teams.push({ pick, players: built.players });
  }

  const text = renderFile(teams);
  if (check) {
    const committed = await readFile(OUTPUT_PATH, 'utf8');
    if (committed !== text) {
      console.error('The committed stockTeams.ts is out of date — re-run the generator.');
      process.exitCode = 1;
    } else {
      console.log(`${STOCK_PICKS.length} stock teams, up to date.`);
    }
    return;
  }

  await writeFile(OUTPUT_PATH, text, 'utf8');
  console.log(`Wrote ${teams.length} stock teams to ${OUTPUT_PATH}`);
  for (const warning of warnings) console.warn(`  warning: ${warning}`);
}

try {
  await main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
