"""lineup and field positions to player

Revision ID: 6924d1f9b260
Revises: a51cf565398f
Create Date: 2023-05-21 20:03:44.157623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6924d1f9b260'
down_revision = 'a51cf565398f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('playerType',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('playerType',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
