"""lineup and positions

Revision ID: a51cf565398f
Revises: 8ab2d82911a4
Create Date: 2023-05-21 03:26:55.307382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51cf565398f'
down_revision = '8ab2d82911a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lineup_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_position', sa.String(length=30), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name_and_year', ['name', 'year'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lineup', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('fieldPositions', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('fieldPositions')
        batch_op.drop_column('lineup')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name_and_year', type_='unique')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('field_position')
        batch_op.drop_column('lineup_position')

    # ### end Alembic commands ###
