"""empty message

Revision ID: df7e7882c19d
Revises: 
Create Date: 2023-05-18 19:38:20.040948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7e7882c19d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), server_default='default_status', nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('in_lineup')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_lineup', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
